### ISSUE TITLE
License conflicts

### ISSUE THREAD

**Issue by ecki** [x-stream/mxparser#2]
The license in the actual .java file and the license.md have different versions, it would be good to unify on the newer license in the .java file 

Indiana University Extreme! Lab Software License, Version 1.2

also the Test Class has a different ASL 2.0 license which should probably be documented as well. Also the Indiana uniersity license has a usage announcement clause, so it’s probably best to mention this in a NOTICE file?

**Comment by joehni** [comment]
Hehe, good catch. I did not modify anything of this, all is in its original shape, see aslom/xpp3. However, since this fork contains only the MXParser and it has been explicitly attributed with version 1.2 of the Indiana license, I think it is valid to replace the LICENSE.txt for this project.
