### ISSUE TITLE
Where to find xmlpull

### ISSUE THREAD

**Issue by roptat** [x-stream/mxparser#3]
Hi!

I'm trying to package mxparser for my distribution, in an attempt to update xstream package. However, we do not have `xmlpull` yet in the distribution, and as we insist to build everything from source, we need to get it first. It seems that, as noted in the readme, Extreme! Lab, Indiana University has closed their website, and the source release have vanished. Do you by any chance know where I can find these sources so I can rebuild my own version of that dependency?

Thanks!

**Comment by joehni** [comment]
See the original repository of this fork: aslom/xpp3. It contains apart form the MXParser also the XmlPull API .

**Comment by roptat** [comment]
Thanks a lot for the timely answer! There's no fork relationship between this repository and `aslom/xpp3`, so it wasn't that easy for me to find out. Now I see it's mentioned in the first commit. Thanks again! I'll be able to package this soon :D
