### ISSUE TITLE
MXParser doesn't parse Process Instructions containing unbalanced SmallerThan/GreaterThan signs

### ISSUE THREAD

**Issue by AmitAmar** [x-stream/mxparser#4]
I'm using xstream version 1.4.15 and I'm trying to upgrade to version: 1.4.17 without success.

The reason of failure is because I have files that contains <?ignore ....... ->

that contains -- (multiple times the character '-')

The parser doesn't ignore it. In Xstrean version 1.4.15 it works great.

I got this execption:

XmlPullParserException: processing instruction started on line 20 and column 5 was not closed (position: END_TAG seen ...\t\t+---------->| Entered Assigned Unit\t|-------------------------->... @48:88)

How I can solve this issue and ignore this "<?ignore" section?

Thank you very much and have a nice day,

Amit.

**Comment by joehni** [comment]
Please provide a real example, otherwise I have to close this issue as invalid. According your description, the following XML should cause the MXParser to fail, but it succeeds:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project>
<?ignore
+-----------------+
?>
</project>

```

**Comment by AmitAmar** [comment]
Hi,

try to use this xml:

	<?ignore
                +-------+
                | RRRRRR|
                +-------+
                    |
                    | [Start AAAA
                    |  BB BBB BBBB]
                    |
                   \|/
                    V
            +--------------+
            | In GGGG        |
            | TTT EEE QQQQQ  |
            +--------------+
                    |
                    |	[DDD FFF GGGG] \ [DDD GFGG] +--------------+
                    |-------------------------------------------> | GGGG FFFF |
                    |											  +--------------+
                    |													    /|\
                    |														 |
                    |	[L.R In an DDD GGG CCC] +-----------------+    | [L.R. BBB of DDD DDDD] /
                    |-------------------------------->| In CCC 	    |	 | [GGGG GGGG GGG] / [Stop CCCC]
                    |								  | VV BBB |----+
                    |								  +-----------------+
                    | [Time BBBB]
                    |
                   \|/
                    V
                +-------+
                | DONE! |
                +-------+
            ?>

BR,

Amit
